extends: default
rules:
  braces:
    level: error
    max-spaces-inside: 0
    min-spaces-inside: 0
  brackets:
    level: error
    max-spaces-inside: 0
    min-spaces-inside: 0
  document-start: {present: false}
  empty-lines: {max: 1}
  indentation: {spaces: 2}
  key-duplicates: {}
  line-length: {max: 120, allow-non-breakable-inline-mappings: true}
  quoted-strings: {quote-type: double, required: only-when-needed}
  trailing-spaces: {}
  truthy: {}
