export default {
  extends: [
    'stylelint-config-html',
    'stylelint-config-recess-order',
    'stylelint-config-standard',
    'stylelint-config-standard-scss',
    '@stylistic/stylelint-plugin',
  ],
  overrides: [],
  plugins: ['@stylistic/stylelint-plugin'],
  rules: {
    '@stylistic/color-hex-case': 'lower',
    '@stylistic/declaration-bang-space-after': 'never',
    '@stylistic/declaration-bang-space-before': 'always',
    '@stylistic/declaration-block-semicolon-newline-after': 'always',
    '@stylistic/declaration-colon-space-before': 'never',
    '@stylistic/function-max-empty-lines': 0,
    '@stylistic/function-parentheses-newline-inside': 'never-multi-line',
    '@stylistic/function-parentheses-space-inside': 'never',
    '@stylistic/function-whitespace-after': 'always',
    '@stylistic/indentation': [2, { baseIndentLevel: 0, indentInsideParens: 'once-at-root-twice-in-block' }],
    '@stylistic/linebreaks': 'unix',
    '@stylistic/max-empty-lines': 1,
    '@stylistic/max-line-length': [120, { ignore: ['comments', 'non-comments'] }],
    '@stylistic/no-empty-first-line': true,
    '@stylistic/no-extra-semicolons': true,
    '@stylistic/number-leading-zero': 'always',
    '@stylistic/number-no-trailing-zeros': true,
    '@stylistic/property-case': 'lower',
    '@stylistic/string-quotes': 'double',
    '@stylistic/unit-case': 'lower',
    '@stylistic/value-list-max-empty-lines': 0,
    'at-rule-empty-line-before': [
      'always',
      { except: ['blockless-after-same-name-blockless'], ignore: ['after-comment'] },
    ],
    'at-rule-no-unknown': [true, { ignoreAtRules: 'use' }],
    'declaration-block-no-duplicate-properties': true,
    'declaration-property-value-no-unknown': true,
    'import-notation': 'string',
    'length-zero-no-unit': true,
    'media-query-no-invalid': null,
    'no-descending-specificity': null,
    'no-irregular-whitespace': true,
    'property-no-vendor-prefix': null,
    'rule-empty-line-before': [
      'always-multi-line',
      {
        ignore: ['first-nested', 'after-comment'],
      },
    ],
    'selector-pseudo-element-no-unknown': [true, { ignorePseudoElements: ['/^v-/'] }],
    'shorthand-property-no-redundant-values': true,
  },
}
